/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FaceAFaceRouteImport } from './routes/face-a-face'
import { Route as LiveRouteImport } from './routes/live'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as PlayRouteImport } from './routes/play'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as TalkShowRouteImport } from './routes/talk-show'
import { Route as MessagesIdRouteImport } from './routes/messages_.$id'
import { Route as PlayFaceAFaceRouteImport } from './routes/play_.face-a-face'
import { Route as PlayHotSeatRouteImport } from './routes/play_.hot-seat'
import { Route as PlayQuizRouteImport } from './routes/play_.quiz'
import { Route as TableIdRouteImport } from './routes/table.$id'
import { Route as TalkShowIndexRouteImport } from './routes/talk-show.index'
import { Route as TalkShowIdRouteImport } from './routes/talk-show.$id'
import { Route as TalkShowOpenMicRouteImport } from './routes/talk-show.open-mic'
import { Route as TalkShowSlamRouteImport } from './routes/talk-show.slam'
import { Route as TalkShowStandRouteImport } from './routes/talk-show.stand'
import { Route as TalkShowStorytellingRouteImport } from './routes/talk-show.storytelling'
import { Route as TalkShowStorytimeRouteImport } from './routes/talk-show.storytime'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FaceAFaceRoute = FaceAFaceRouteImport.update({
  id: '/face-a-face',
  path: '/face-a-face',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const TalkShowRoute = TalkShowRouteImport.update({
  id: '/talk-show',
  path: '/talk-show',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIdRoute = MessagesIdRouteImport.update({
  id: '/messages_/$id',
  path: '/messages/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayFaceAFaceRoute = PlayFaceAFaceRouteImport.update({
  id: '/play_/face-a-face',
  path: '/play/face-a-face',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayHotSeatRoute = PlayHotSeatRouteImport.update({
  id: '/play_/hot-seat',
  path: '/play/hot-seat',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayQuizRoute = PlayQuizRouteImport.update({
  id: '/play_/quiz',
  path: '/play/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const TableIdRoute = TableIdRouteImport.update({
  id: '/table/$id',
  path: '/table/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TalkShowIndexRoute = TalkShowIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TalkShowRoute,
} as any)
const TalkShowIdRoute = TalkShowIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TalkShowRoute,
} as any)
const TalkShowOpenMicRoute = TalkShowOpenMicRouteImport.update({
  id: '/open-mic',
  path: '/open-mic',
  getParentRoute: () => TalkShowRoute,
} as any)
const TalkShowSlamRoute = TalkShowSlamRouteImport.update({
  id: '/slam',
  path: '/slam',
  getParentRoute: () => TalkShowRoute,
} as any)
const TalkShowStandRoute = TalkShowStandRouteImport.update({
  id: '/stand',
  path: '/stand',
  getParentRoute: () => TalkShowRoute,
} as any)
const TalkShowStorytellingRoute = TalkShowStorytellingRouteImport.update({
  id: '/storytelling',
  path: '/storytelling',
  getParentRoute: () => TalkShowRoute,
} as any)
const TalkShowStorytimeRoute = TalkShowStorytimeRouteImport.update({
  id: '/storytime',
  path: '/storytime',
  getParentRoute: () => TalkShowRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/face-a-face': typeof FaceAFaceRoute
  '/live': typeof LiveRoute
  '/messages': typeof MessagesRoute
  '/play': typeof PlayRoute
  '/profile': typeof ProfileRoute
  '/talk-show': typeof TalkShowRouteWithChildren
  '/messages/$id': typeof MessagesIdRoute
  '/play/face-a-face': typeof PlayFaceAFaceRoute
  '/play/hot-seat': typeof PlayHotSeatRoute
  '/play/quiz': typeof PlayQuizRoute
  '/table/$id': typeof TableIdRoute
  '/talk-show/$id': typeof TalkShowIdRoute
  '/talk-show/open-mic': typeof TalkShowOpenMicRoute
  '/talk-show/slam': typeof TalkShowSlamRoute
  '/talk-show/stand': typeof TalkShowStandRoute
  '/talk-show/storytelling': typeof TalkShowStorytellingRoute
  '/talk-show/storytime': typeof TalkShowStorytimeRoute
  '/talk-show/': typeof TalkShowIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/face-a-face': typeof FaceAFaceRoute
  '/live': typeof LiveRoute
  '/messages': typeof MessagesRoute
  '/play': typeof PlayRoute
  '/profile': typeof ProfileRoute
  '/messages/$id': typeof MessagesIdRoute
  '/play/face-a-face': typeof PlayFaceAFaceRoute
  '/play/hot-seat': typeof PlayHotSeatRoute
  '/play/quiz': typeof PlayQuizRoute
  '/table/$id': typeof TableIdRoute
  '/talk-show/$id': typeof TalkShowIdRoute
  '/talk-show/open-mic': typeof TalkShowOpenMicRoute
  '/talk-show/slam': typeof TalkShowSlamRoute
  '/talk-show/stand': typeof TalkShowStandRoute
  '/talk-show/storytelling': typeof TalkShowStorytellingRoute
  '/talk-show/storytime': typeof TalkShowStorytimeRoute
  '/talk-show': typeof TalkShowIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/face-a-face': typeof FaceAFaceRoute
  '/live': typeof LiveRoute
  '/messages': typeof MessagesRoute
  '/play': typeof PlayRoute
  '/profile': typeof ProfileRoute
  '/talk-show': typeof TalkShowRouteWithChildren
  '/messages_/$id': typeof MessagesIdRoute
  '/play_/face-a-face': typeof PlayFaceAFaceRoute
  '/play_/hot-seat': typeof PlayHotSeatRoute
  '/play_/quiz': typeof PlayQuizRoute
  '/table/$id': typeof TableIdRoute
  '/talk-show/$id': typeof TalkShowIdRoute
  '/talk-show/open-mic': typeof TalkShowOpenMicRoute
  '/talk-show/slam': typeof TalkShowSlamRoute
  '/talk-show/stand': typeof TalkShowStandRoute
  '/talk-show/storytelling': typeof TalkShowStorytellingRoute
  '/talk-show/storytime': typeof TalkShowStorytimeRoute
  '/talk-show/': typeof TalkShowIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/face-a-face'
    | '/live'
    | '/messages'
    | '/play'
    | '/profile'
    | '/talk-show'
    | '/messages/$id'
    | '/play/face-a-face'
    | '/play/hot-seat'
    | '/play/quiz'
    | '/table/$id'
    | '/talk-show/$id'
    | '/talk-show/open-mic'
    | '/talk-show/slam'
    | '/talk-show/stand'
    | '/talk-show/storytelling'
    | '/talk-show/storytime'
    | '/talk-show/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/face-a-face'
    | '/live'
    | '/messages'
    | '/play'
    | '/profile'
    | '/messages/$id'
    | '/play/face-a-face'
    | '/play/hot-seat'
    | '/play/quiz'
    | '/table/$id'
    | '/talk-show/$id'
    | '/talk-show/open-mic'
    | '/talk-show/slam'
    | '/talk-show/stand'
    | '/talk-show/storytelling'
    | '/talk-show/storytime'
    | '/talk-show'
  id:
    | '__root__'
    | '/'
    | '/face-a-face'
    | '/live'
    | '/messages'
    | '/play'
    | '/profile'
    | '/talk-show'
    | '/messages_/$id'
    | '/play_/face-a-face'
    | '/play_/hot-seat'
    | '/play_/quiz'
    | '/table/$id'
    | '/talk-show/$id'
    | '/talk-show/open-mic'
    | '/talk-show/slam'
    | '/talk-show/stand'
    | '/talk-show/storytelling'
    | '/talk-show/storytime'
    | '/talk-show/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FaceAFaceRoute: typeof FaceAFaceRoute
  LiveRoute: typeof LiveRoute
  MessagesRoute: typeof MessagesRoute
  PlayRoute: typeof PlayRoute
  ProfileRoute: typeof ProfileRoute
  TalkShowRoute: typeof TalkShowRouteWithChildren
  MessagesIdRoute: typeof MessagesIdRoute
  PlayFaceAFaceRoute: typeof PlayFaceAFaceRoute
  PlayHotSeatRoute: typeof PlayHotSeatRoute
  PlayQuizRoute: typeof PlayQuizRoute
  TableIdRoute: typeof TableIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/face-a-face': {
      id: '/face-a-face'
      path: '/face-a-face'
      fullPath: '/face-a-face'
      preLoaderRoute: typeof FaceAFaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talk-show': {
      id: '/talk-show'
      path: '/talk-show'
      fullPath: '/talk-show'
      preLoaderRoute: typeof TalkShowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages_/$id': {
      id: '/messages_/$id'
      path: '/messages/$id'
      fullPath: '/messages/$id'
      preLoaderRoute: typeof MessagesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play_/face-a-face': {
      id: '/play_/face-a-face'
      path: '/play/face-a-face'
      fullPath: '/play/face-a-face'
      preLoaderRoute: typeof PlayFaceAFaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play_/hot-seat': {
      id: '/play_/hot-seat'
      path: '/play/hot-seat'
      fullPath: '/play/hot-seat'
      preLoaderRoute: typeof PlayHotSeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play_/quiz': {
      id: '/play_/quiz'
      path: '/play/quiz'
      fullPath: '/play/quiz'
      preLoaderRoute: typeof PlayQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table/$id': {
      id: '/table/$id'
      path: '/table/$id'
      fullPath: '/table/$id'
      preLoaderRoute: typeof TableIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talk-show/': {
      id: '/talk-show/'
      path: '/'
      fullPath: '/talk-show/'
      preLoaderRoute: typeof TalkShowIndexRouteImport
      parentRoute: typeof TalkShowRoute
    }
    '/talk-show/$id': {
      id: '/talk-show/$id'
      path: '/$id'
      fullPath: '/talk-show/$id'
      preLoaderRoute: typeof TalkShowIdRouteImport
      parentRoute: typeof TalkShowRoute
    }
    '/talk-show/open-mic': {
      id: '/talk-show/open-mic'
      path: '/open-mic'
      fullPath: '/talk-show/open-mic'
      preLoaderRoute: typeof TalkShowOpenMicRouteImport
      parentRoute: typeof TalkShowRoute
    }
    '/talk-show/slam': {
      id: '/talk-show/slam'
      path: '/slam'
      fullPath: '/talk-show/slam'
      preLoaderRoute: typeof TalkShowSlamRouteImport
      parentRoute: typeof TalkShowRoute
    }
    '/talk-show/stand': {
      id: '/talk-show/stand'
      path: '/stand'
      fullPath: '/talk-show/stand'
      preLoaderRoute: typeof TalkShowStandRouteImport
      parentRoute: typeof TalkShowRoute
    }
    '/talk-show/storytelling': {
      id: '/talk-show/storytelling'
      path: '/storytelling'
      fullPath: '/talk-show/storytelling'
      preLoaderRoute: typeof TalkShowStorytellingRouteImport
      parentRoute: typeof TalkShowRoute
    }
    '/talk-show/storytime': {
      id: '/talk-show/storytime'
      path: '/storytime'
      fullPath: '/talk-show/storytime'
      preLoaderRoute: typeof TalkShowStorytimeRouteImport
      parentRoute: typeof TalkShowRoute
    }
  }
}

interface TalkShowRouteChildren {
  TalkShowIdRoute: typeof TalkShowIdRoute
  TalkShowOpenMicRoute: typeof TalkShowOpenMicRoute
  TalkShowSlamRoute: typeof TalkShowSlamRoute
  TalkShowStandRoute: typeof TalkShowStandRoute
  TalkShowStorytellingRoute: typeof TalkShowStorytellingRoute
  TalkShowStorytimeRoute: typeof TalkShowStorytimeRoute
  TalkShowIndexRoute: typeof TalkShowIndexRoute
}

const TalkShowRouteChildren: TalkShowRouteChildren = {
  TalkShowIdRoute: TalkShowIdRoute,
  TalkShowOpenMicRoute: TalkShowOpenMicRoute,
  TalkShowSlamRoute: TalkShowSlamRoute,
  TalkShowStandRoute: TalkShowStandRoute,
  TalkShowStorytellingRoute: TalkShowStorytellingRoute,
  TalkShowStorytimeRoute: TalkShowStorytimeRoute,
  TalkShowIndexRoute: TalkShowIndexRoute,
}

const TalkShowRouteWithChildren = TalkShowRoute._addFileChildren(
  TalkShowRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FaceAFaceRoute: FaceAFaceRoute,
  LiveRoute: LiveRoute,
  MessagesRoute: MessagesRoute,
  PlayRoute: PlayRoute,
  ProfileRoute: ProfileRoute,
  TalkShowRoute: TalkShowRouteWithChildren,
  MessagesIdRoute: MessagesIdRoute,
  PlayFaceAFaceRoute: PlayFaceAFaceRoute,
  PlayHotSeatRoute: PlayHotSeatRoute,
  PlayQuizRoute: PlayQuizRoute,
  TableIdRoute: TableIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
