/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LiveRouteImport } from './routes/live'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as PlayRouteImport } from './routes/play'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MessagesIdRouteImport } from './routes/messages_.$id'
import { Route as PlayQuizRouteImport } from './routes/play_.quiz'
import { Route as TableIdRouteImport } from './routes/table.$id'
import { Route as TalkShowIdRouteImport } from './routes/talk-show.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIdRoute = MessagesIdRouteImport.update({
  id: '/messages_/$id',
  path: '/messages/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayQuizRoute = PlayQuizRouteImport.update({
  id: '/play_/quiz',
  path: '/play/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const TableIdRoute = TableIdRouteImport.update({
  id: '/table/$id',
  path: '/table/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TalkShowIdRoute = TalkShowIdRouteImport.update({
  id: '/talk-show/$id',
  path: '/talk-show/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/live': typeof LiveRoute
  '/messages': typeof MessagesRoute
  '/play': typeof PlayRoute
  '/profile': typeof ProfileRoute
  '/messages/$id': typeof MessagesIdRoute
  '/play/quiz': typeof PlayQuizRoute
  '/table/$id': typeof TableIdRoute
  '/talk-show/$id': typeof TalkShowIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/live': typeof LiveRoute
  '/messages': typeof MessagesRoute
  '/play': typeof PlayRoute
  '/profile': typeof ProfileRoute
  '/messages/$id': typeof MessagesIdRoute
  '/play/quiz': typeof PlayQuizRoute
  '/table/$id': typeof TableIdRoute
  '/talk-show/$id': typeof TalkShowIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/live': typeof LiveRoute
  '/messages': typeof MessagesRoute
  '/play': typeof PlayRoute
  '/profile': typeof ProfileRoute
  '/messages_/$id': typeof MessagesIdRoute
  '/play_/quiz': typeof PlayQuizRoute
  '/table/$id': typeof TableIdRoute
  '/talk-show/$id': typeof TalkShowIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/live'
    | '/messages'
    | '/play'
    | '/profile'
    | '/messages/$id'
    | '/play/quiz'
    | '/table/$id'
    | '/talk-show/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/live'
    | '/messages'
    | '/play'
    | '/profile'
    | '/messages/$id'
    | '/play/quiz'
    | '/table/$id'
    | '/talk-show/$id'
  id:
    | '__root__'
    | '/'
    | '/live'
    | '/messages'
    | '/play'
    | '/profile'
    | '/messages_/$id'
    | '/play_/quiz'
    | '/table/$id'
    | '/talk-show/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LiveRoute: typeof LiveRoute
  MessagesRoute: typeof MessagesRoute
  PlayRoute: typeof PlayRoute
  ProfileRoute: typeof ProfileRoute
  MessagesIdRoute: typeof MessagesIdRoute
  PlayQuizRoute: typeof PlayQuizRoute
  TableIdRoute: typeof TableIdRoute
  TalkShowIdRoute: typeof TalkShowIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages_/$id': {
      id: '/messages_/$id'
      path: '/messages/$id'
      fullPath: '/messages/$id'
      preLoaderRoute: typeof MessagesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play_/quiz': {
      id: '/play_/quiz'
      path: '/play/quiz'
      fullPath: '/play/quiz'
      preLoaderRoute: typeof PlayQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table/$id': {
      id: '/table/$id'
      path: '/table/$id'
      fullPath: '/table/$id'
      preLoaderRoute: typeof TableIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talk-show/$id': {
      id: '/talk-show/$id'
      path: '/talk-show/$id'
      fullPath: '/talk-show/$id'
      preLoaderRoute: typeof TalkShowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LiveRoute: LiveRoute,
  MessagesRoute: MessagesRoute,
  PlayRoute: PlayRoute,
  ProfileRoute: ProfileRoute,
  MessagesIdRoute: MessagesIdRoute,
  PlayQuizRoute: PlayQuizRoute,
  TableIdRoute: TableIdRoute,
  TalkShowIdRoute: TalkShowIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
